apiVersion: v1
kind: Namespace
metadata:
  name: mimi2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mimi2-config
  namespace: mimi2
data:
  OLLAMA_URL: "http://ollama:11434"
  OLLAMA_MODEL: "gpt-oss:20b"
  OPENAI_API_KEY: "ollama"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimi2
  namespace: mimi2
  labels:
    app: mimi2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimi2
  template:
    metadata:
      labels:
        app: mimi2
    spec:
      containers:
      - name: mimi2
        image: ghcr.io/xe/mimi2:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: mimi2-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: false
---
apiVersion: v1
kind: Service
metadata:
  name: mimi2
  namespace: mimi2
  labels:
    app: mimi2
spec:
  selector:
    app: mimi2
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: mimi2
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
      volumes:
      - name: ollama-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: mimi2
  labels:
    app: ollama
spec:
  selector:
    app: ollama
  ports:
  - name: http
    port: 11434
    targetPort: 11434
  type: ClusterIP